const reports = {
    "NCR-001": {
        process: "supplier",
        supplier: "Maple Industrial Supplies",
        ncrNumber: "NCR-001",
        reference: "PO-45821",
        salesOrder: "SO-78210",
        item: "Steel mounting bracket, SAP No. 104582",
        received: "20",
        defective: "3",
        defect: "Three brackets have cracks near the mounting holes.",
        marked: "yes",
        qualityRep: "Sarah Wilson",
        qualityDate: "2026-10-01",
        additional: "Inspection photos show cracks beside the mounting holes.",
        disposition: "rework",
        notify: "no",
        workSteps: "Return the cracked brackets for rework. Inspect the mounting holes and verify dimensions before acceptance.",
        drawing: "no",
        originalRev: "",
        updatedRev: "",
        engineerName: "",
        revisionDate: "",
        engineering: "Daniel Chen",
        engineeringDate: "2026-10-02",
        purchasing: "return",
        car: "yes",
        carNumber: "CAR-026",
        followUp: "yes",
        followDetails: "Confirm reworked bracket delivery by 2026-10-06.",
        operations: "Amina Hassan",
        operationsDate: "2026-10-03",
        acceptable: "yes",
        newNcr: "",
        inspector: "James Carter",
        inspectionDate: "2026-10-07",
        closed: "yes",
        qualityDepartment: "Sarah Wilson",
        closedDate: "2026-10-08"
    },

    "NCR-002": {
        process: "wip",
        supplier: "Northern Metalworks",
        ncrNumber: "NCR-002",
        reference: "PROD-63142",
        salesOrder: "SO-78235",
        item: "Aluminium enclosure panel, SAP No. 207316",
        received: "15",
        defective: "2",
        defect: "Two panels were scratched during assembly, exposing the metal beneath the coating.",
        marked: "yes",
        qualityRep: "Omar Ali",
        qualityDate: "2026-10-02",
        additional: "Surface inspection photos document the coating damage.",
        disposition: "repair",
        notify: "no",
        workSteps: "Repair the coating using the approved procedure. Inspect the repaired finish before release.",
        drawing: "no",
        originalRev: "",
        updatedRev: "",
        engineerName: "",
        revisionDate: "",
        engineering: "Emily Parker",
        engineeringDate: "2026-10-03",
        purchasing: "in-house",
        car: "no",
        carNumber: "",
        followUp: "no",
        followDetails: "",
        operations: "Michael Brown",
        operationsDate: "2026-10-04",
        acceptable: "yes",
        newNcr: "",
        inspector: "Priya Shah",
        inspectionDate: "2026-10-06",
        closed: "yes",
        qualityDepartment: "Omar Ali",
        closedDate: "2026-10-07"
    },

    "NCR-003": {
        process: "supplier",
        supplier: "Precision Fastener Supply",
        ncrNumber: "NCR-003",
        reference: "PO-45903",
        salesOrder: "SO-78301",
        item: "M12 × 40 mm hex bolt, SAP No. 309724",
        received: "50",
        defective: "10",
        defect: "Ten bolts measure 35 mm in length instead of the specified 40 mm.",
        marked: "yes",
        qualityRep: "Grace Thompson",
        qualityDate: "2026-10-01",
        additional: "Measurement records confirm the incorrect bolt lengths.",
        disposition: "scrap",
        notify: "no",
        workSteps: "Segregate and scrap the incorrect bolts. Obtain replacement bolts and verify their lengths.",
        drawing: "no",
        originalRev: "",
        updatedRev: "",
        engineerName: "",
        revisionDate: "",
        engineering: "Ahmed Khan",
        engineeringDate: "2026-10-02",
        purchasing: "scrap",
        car: "yes",
        carNumber: "CAR-027",
        followUp: "yes",
        followDetails: "Review the supplier's corrective action by 2026-10-07.",
        operations: "Olivia Martin",
        operationsDate: "2026-10-03",
        acceptable: "yes",
        newNcr: "",
        inspector: "Lucas Bennett",
        inspectionDate: "2026-10-07",
        closed: "yes",
        qualityDepartment: "Grace Thompson",
        closedDate: "2026-10-08"
    }
};